name: Generate RSS Feed

on:
  schedule:
    - cron: '0 6 * * 6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate RSS
        run: python generate_rss.py

      - name: Commit and push changes
        run: |
          git config --global user.name "rss-bot"
          git config --global user.email "bot@example.com"
          git add feed.xml
          git commit -m "Update RSS feed" || echo "No changes"
          git push
